# FenrirOS mkinitcpio.conf
# For the INSTALLED system - uses udev (not systemd hook)

MODULES=()
BINARIES=()
FILES=()
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)
