---
# FenrirOS initcpiocfg module
# Configures mkinitcpio for the installed system
# Uses standard hooks with autodetect for installed systems

kernel: linux-cachyos

HOOKS:
    - base
    - udev
    - autodetect
    - modconf
    - kms
    - keyboard
    - keymap
    - consolefont
    - block
    - filesystems
    - fsck

MODULES: []
BINARIES: []
FILES: []
