---
initDir: /etc/init.d
runlevelsDir: /etc/runlevels

services:
    - name: udev
      mandatory: true
      runlevel: sysinit

    - name: dbus
      mandatory: true
      runlevel: default

    - name: elogind
      mandatory: true
      runlevel: default

    - name: NetworkManager
      mandatory: true
      runlevel: default

    - name: sddm
      mandatory: true
      runlevel: default

    - name: acpid
      mandatory: false
      runlevel: default

    - name: cronie
      mandatory: false
      runlevel: default

    - name: gamemoded
      mandatory: false
      runlevel: default
