---
# FenrirOS users module

defaultGroups:
    - audio
    - video
    - wheel
    - storage
    - optical
    - input
    - network
    - gamemode

autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: false
passwordRequirements:
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=0
        - minclass=0
avatarFilePath: ~/.face
